# Generated by Django 2.2.3 on 2019-07-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='upvotes',
            new_name='votes',
        ),
    ]
