# Generated by Django 2.2.3 on 2019-07-13 05:55

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190712_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='votes',
        ),
        migrations.AddField(
            model_name='ticket',
            name='votes',
            field=models.IntegerField(default=0, verbose_name=django.contrib.auth.models.User),
        ),
    ]
