# Generated by Django 2.2.3 on 2019-07-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20190713_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
