# Generated by Django 2.2.3 on 2019-07-14 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20190713_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='votes',
            new_name='votes_total',
        ),
    ]
