# Generated by Django 2.2.3 on 2019-07-15 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0006_auto_20190714_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='votes_total',
        ),
        migrations.AddField(
            model_name='ticket',
            name='votes_total',
            field=models.ManyToManyField(blank=True, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
