# Generated by Django 2.2.3 on 2019-07-17 08:30

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20190715_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='votes_total',
        ),
        migrations.AddField(
            model_name='ticket',
            name='votes_total',
            field=models.IntegerField(blank=True, default=0, verbose_name=django.contrib.auth.models.User),
        ),
    ]
