# Generated by Django 2.2.3 on 2019-07-17 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0009_auto_20190717_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='votes',
        ),
        migrations.AddField(
            model_name='ticket',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
