# Generated by Django 2.2.3 on 2019-07-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20190717_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='money_raised',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
